[package]
name = "clipboard-cleaner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "4.5.0"
image = "0.24.7"
tao = "0.23.0"
tray-icon = "0.10.0"
